### ISSUE TITLE
require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by haripri-vt** [ricardoaponte/vue3-spinner#1]
I am getting the following error from vue3-spinner dependency:
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/Code/master/frontend/node_modules/vue3-spinner/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/Code/master/frontend/node_modules/vue3-spinner/lib/vue3-spinner.js:3:11
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:526:24)

**Comment by capoia** [comment]
Same problem here.

**Comment by marr** [comment]
in package.json:

```
"exports": {
    ".": {
      "import": "./lib/vue3-spinner.js",
      "require": "./lib/vue3-spinner.js"
    }
  },
```

should be:
```
"exports": {
    ".": {
      "import": "./lib/vue3-spinner.mjs",
      "require": "./lib/vue3-spinner.js"
    }
  },
```
